jobs:
- job: build_geoip
  timeoutInMinutes: 30

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    GOPATH: '$(system.defaultWorkingDirectory)'

  steps:
  - checkout: self
  - task: GoTool@0
    inputs:
      version: '1.11.2'
  - script: |
      go version
      chmod +x $(Build.SourcesDirectory)/generate.sh
      $(Build.SourcesDirectory)/generate.sh
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Generate'
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(system.defaultworkingdirectory)/publish'
      contents: 'geoip.dat'
      targetFolder: '$(build.artifactStagingDirectory)'
  - task: GithubRelease@0
    displayName: 'Upload to Github'
    inputs:
      gitHubConnection: GithubRelease
      repositoryName: 'v2ray/geoip'
      action: 'create'
      target: '$(build.sourceVersion)'
      tagSource: 'manual'
      releaseNotesSource: 'input'
      releaseNotes: 'Weekly Geoip Release'
      assets: '$(build.artifactStagingDirectory)/geoip.dat'
