jobs:
- job: build_geoip
  timeoutInMinutes: 30

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    GOPATH: '$(system.defaultWorkingDirectory)'

  steps:
  - checkout: self
  - task: GoTool@0
    inputs:
      version: '1.11.2'
  - script: |
      go version
      chmod +x $(Build.SourcesDirectory)/generate.sh
      $(Build.SourcesDirectory)/generate.sh
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Generate'
  - task: GithubRelease@0
    displayName: 'CreateRelease'
    inputs:
      gitHubConnection: GithubRelease
      repositoryName: 'v2ray/geoip'
      action: 'create'
      target: '$(build.sourceVersion)'
      tagSource: 'manual'
      tag: '$(Build.BuildNumber)'
      releaseNotesSource: 'input'
      releaseNotes: 'Weekly Geoip Release'
      assets: '$(system.defaultWorkingDirectory)/publish/geoip.dat'
      assetUploadMode: 'delete' # Optional. Options: delete, replace
      #isDraft: false # Optional
      #isPreRelease: false # Optional
      #addChangeLog: true # Optional
